### ISSUE TITLE
Add listener to stop recording

### ISSUE THREAD

**Issue by 0dm** [OpenAdaptAI/OpenAdapt#150]
We should add a listener for a key combination that stops recordings (default to ctrl+c, but preferably configurable) so that users don’t have to send SIGINT by interacting with the terminal. This would remove an unnecessary last-step of recordings.

I recommend we use pynput for this, since we already use it for other purposes - rough idea:
```py
# On Key Pressed Event                      
def on_press(key):
   ...

with kb.Listener(
        on_press=on_press) as listener:
    listener.join()
    ```

**Comment by 0dm** [comment]
It'd be best to run a check during recordings, while ActionEvents are being created.

**Comment by abrichr** [comment]
Related: https://github.com/MLDSAI/OpenAdapt/pull/139
