### ISSUE TITLE
Expand on DemoReplayStrategy

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#24]
How can we modify the [DemoReplayStrategy](https://github.com/MLDSAI/puterbot/blob/main/puterbot/strategies/demo.py) that uses the available primitives (e.g. LLMs, OCR, SVG, etc) in a way that makes sense?

**Comment by dianzrong** [comment]
Hi, 
I would love to work on this issue, however, I'm confused as to what this issue is asking for. Could I get some further clarification? 
Thanks!

**Comment by abrichr** [comment]
HI @dianzrong, thank you for your interest in this issue!

From [demo.py](https://github.com/MLDSAI/puterbot/blob/main/puterbot/strategies/demo.py):

```
    def get_next_input_event(
        self,
        screenshot: Screenshot,
    ):
        ascii_text = self.get_ascii_text(screenshot)
        #logger.info(f"ascii_text=\n{ascii_text}")

        ocr_text = self.get_ocr_text(screenshot)
        #logger.info(f"ocr_text=\n{ocr_text}")

        event_strs = [
            f"<{event}>"
            for event in self.recording.input_events
        ]
        history_strs = [
            f"<{completion}>"
            for completion in self.result_history
        ]
        prompt = " ".join(event_strs + history_strs)
        N = max(0, len(prompt) - MAX_INPUT_SIZE)
        prompt = prompt[N:]
        logger.info(f"{prompt=}")
        max_tokens = 10
        completion = self.get_completion(prompt, max_tokens)
        logger.info(f"{completion=}")

        # only take the first <...>
        result = completion.split(">")[0].strip(" <>")
        logger.info(f"{result=}")
        self.result_history.append(result)

        # TODO: parse result into InputEvent(s)

        return None
```

This code is converting the screenshot into text using ASCII and OCR, but the values of `ascii_text` and `ocr_text` are not used when generating a completion. This means that the language model is generating completions solely based on the `InputEvent`s in the recording, ignoring the screenshots altogether.

Imagine if a person were asked to accomplish a task by only looking at input events. Maybe they could memorize them, but if anything changed on the screen they wouldn't know. The same is true for the model.

This task involves thinking about how to combine the `ocr_text` and/or `ascii_text` with the `InputEvent`s to generate the prompt.

Does that clarify things?

**Comment by dianzrong** [comment]
@abrichr, yes that does. Thank you so much!!
