### ISSUE TITLE
Explore OpenLLM

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#291]
### Feature request

How can we take advantage of https://github.com/bentoml/OpenLLM ?

**Comment by FFFiend** [comment]
So from what I've seen, OpenLLM is a library that makes it easier for you to host web apps and whatnot with language models, i.e querying and displaying on a web server and deploying apps that boast this and other generative tasks as a feature. I spoke to the author about the whole CPU and GPU loading conundrum and it seems like they don't do anything especially useful to make huge models load on CPU's like we want with MPT-7B. 

What we DO want is quantized versions of these huge models to run on CPU, and to that end I found GGML to be the solution here, more in the direction of LLAMA.cpp.

**Comment by FFFiend** [comment]
UPDATE: So I tested MPT-7B 4-bit quantized (https://huggingface.co/TheBloke/MPT-7B-GGML) on my Mac (M2 chip, 8GB CPU RAM) and it generated perfectly. I just used the ctransformer library, and I think we can generate completions for the MPTReplayStrat class in #226 and close it using something like this.. Try it out if you have RAM to spare! (I think you'd need 6+ gigs Free to generate a completion though)

```
from ctransformers import AutoModelForCausalLM

llm = AutoModelForCausalLM.from_pretrained('TheBloke/MPT-7B-GGML', model_type='mpt', model_file='mpt-7b.ggmlv3.q4_0.bin')

completion = "This is "
print(llm(completion))
```

**Comment by abrichr** [comment]
Conclusion: implement https://github.com/OpenAdaptAI/OpenAdapt/pull/303
