### ISSUE TITLE
Progress bar for recording and visualization

### ISSUE THREAD

**Issue by 0dm** [OpenAdaptAI/OpenAdapt#316]
### Feature request

a progress bar after stopping a recording

resources:
https://github.com/tqdm/tqdm (used in scrub already)
or
https://github.com/rsalmei/alive-progress (could be better?)

### Motivation

After recording, I'd like to know when it'll be done writing to the db. I usually just find myself tabbing out and watching the file size grow to gain some sense of progress 😅

**Comment by abrichr** [comment]
Thanks @0dm 🙏  `alive-progress` looks sweet!

**Comment by KrishPatel13** [comment]
@0dm Have you started to work on this ? Or should I take it over ? :)

**Comment by KrishPatel13** [comment]
No worries, I will put a PR for it today! @abrichr

**Comment by KrishPatel13** [comment]
@abrichr /@0dm Should I also include the progress bar for Visualization ?

**Comment by 0dm** [comment]
> @abrichr /@0dm Should I also include the progress bar for Visualization ?

That'd be pretty nice, there already is some indication of when it finishes if you count the number of action events it processes, but a bar would be great.

**Comment by KrishPatel13** [comment]
Cool! So I will include Progress bar for both record and visualize,

**Comment by KrishPatel13** [comment]
Some visuals for the Progress bar during Visualization:
![clideo_editor_914f802dd3c246e4836b5b2d96de8115](https://github.com/MLDSAI/OpenAdapt/assets/65433817/28ad065a-2ca6-4017-a8f5-86329dc06227)

**Comment by KrishPatel13** [comment]
PLease let me know if this progress bar is good to go :?

**Comment by KrishPatel13** [comment]
I will now add in record.py.

**Comment by 0dm** [comment]
> Some visuals for the Progress bar during Visualization:
> ![clideo_editor_914f802dd3c246e4836b5b2d96de8115](https://user-images.githubusercontent.com/65433817/248862156-28ad065a-2ca6-4017-a8f5-86329dc06227.gif)

nice!
