### ISSUE TITLE
Investigate Other Redaction Libraries

### ISSUE THREAD

**Issue by KrishPatel13** [OpenAdaptAI/OpenAdapt#330]
### Feature request

Presidio Image Redaction is not completely reliable right now.
As it not redacting all PII/PHI.

### Motivation

I am frustrated when I investigated https://github.com/MLDSAI/OpenAdapt/pull/328#issuecomment-1611909662  so this feature would Investigate different Image Redaction Libraries, testing on sample Images where Presidio Image Redaction Fails:

eg. https://github.com/MLDSAI/OpenAdapt/pull/328#issuecomment-1611909662

**Comment by KrishPatel13** [comment]
1. OpenRedact
    Github: https://github.com/openredact/anonymizer
    Article: https://medium.com/@openredact/anonymizer-a-framework-for-text-anonymization-499855f639d4
    Other: Related to #272 
       From Article: 
              <img width="535" alt="image" src="https://github.com/MLDSAI/OpenAdapt/assets/65433817/234f32b3-2003-4d01-a941-fa955e595af7">

**Comment by KrishPatel13** [comment]
Other Useful Search Link: https://github.com/topics/data-anonymization?l=python

**Comment by KrishPatel13** [comment]
2. Open-Data-Anonymizer
    > Github: https://github.com/ArtLabss/open-data-anonymizer
    > Useful for Redaction of People Faces (personal images), PDF.
    > See some nice usage examples:
            https://github.com/ArtLabss/open-data-anonymizer

**Comment by KrishPatel13** [comment]
3. [BMW-Anonymization-API](https://github.com/BMW-InnovationLab/BMW-Anonymization-API)
    > Github: https://github.com/BMW-InnovationLab/BMW-Anonymization-API
    > Useful for Video Redaction (specifically, object anonymization like. People faces, identity. etc. )
        https://github.com/BMW-InnovationLab/BMW-Anonymization-API/blob/master/references/output_7.gif

**Comment by KrishPatel13** [comment]
https://docs.capeprivacy.com/getting-started

Cape-Privacy is good!

**Comment by abrichr** [comment]
https://github.com/OpenAdaptAI/OpenAdapt/pull/418

**Comment by KrishPatel13** [comment]
After #486 shall we close this ?
