### ISSUE TITLE
[Bug]: README.md installation does not include tesseract and other dependencies

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#342]
### Describe the bug

Following instructions in https://github.com/OpenAdaptAI/OpenAdapt#install does not succeed if tesseract is not installed.

### To Reproduce

Follow https://github.com/OpenAdaptAI/OpenAdapt#install on a machine without tesseract.

**Comment by KrishPatel13** [comment]
Thank you @abrichr pointing this out.

1 more question before I get started in this. The installation scripts do NOT mention about installation of Python version 3.10 and Git as well. 

Should I add them as well ?

**Comment by abrichr** [comment]
@KrishPatel13 to clarify, I believe https://github.com/OpenAdaptAI/OpenAdapt/blob/main/install/install_openadapt.ps1 installs Python and Git, but https://github.com/OpenAdaptAI/OpenAdapt/blob/main/install/install_openadapt.sh does not.

I believe this is being addressed in https://github.com/OpenAdaptAI/OpenAdapt/pull/244

**Comment by KrishPatel13** [comment]
I have updated the README.md and it now includes the as Prerequisites.

See: https://github.com/OpenAdaptAI/OpenAdapt/blob/1830990156acf436552f124edfa895b6511b6404/README.md#install
