### ISSUE TITLE
[Bug]: windows install script is brittle

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#372]
### Describe the bug

I experienced a few issues running the windows installation script:

1. Any version of git should work

![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/44f7a0b1-0a80-4927-8df5-3a8c363d950d)

2. When the user declines to update git, the installation should continue:

![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/39b5af23-0de7-4506-9b94-ddbc8f137f1d)

3. When the script exits, ideally there should be some sort of message:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\erika> Start-Process powershell -Verb RunAs -ArgumentList '-NoExit', '-ExecutionPolicy', 'Bypass', '-Command', "iwr -UseBasicParsing -Uri 'https://raw.githubusercontent.com/MLDSAI/OpenAdapt/main/install/install_openadapt.ps1' | Invoke-Expression"
PS C:\Users\erika>   
```

4. Ideally we should support any version of python greater or equal to 3.10

![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/26c12498-2360-4205-97b7-0f521e529448)

5. Running `poetry shell` sometimes fails with this message:

![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/3992e5d6-63c2-42da-8a29-11243956340d)

6. Trying to activate it fails, even though it hasn't been activated:

![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/25d70376-37a4-468f-b1f0-05d0cd0cdb77)
![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/aa499cb6-9956-4784-9d50-7f12b0ea144e)

### To Reproduce

See above

**Comment by KrishPatel13** [comment]
Some Improvement in `CheckCMDExists` function:

Old Function Terminal Transcript:
<Add_Image>

Updated Function Code for Terminal Transcript:
```
PS C:\Users\Krish Patel> function CheckCMDExists {
>>     Param
>>     (
>>         [Parameter(Mandatory = $true)] [string] $command
>>     )
>>
>>     $result = Get-Command $command -errorvariable getErr -erroraction 'silentlycontinue'
>>     if ($null -eq $result) {
>>         return $false
>>     }
>>     return $true
>> }
PS C:\Users\Krish Patel> CheckCMDExists "got"
False
PS C:\Users\Krish Patel> CheckCMDExists "git"
True
PS C:\Users\Krish Patel> CheckCMDExists "tesseract"
True
PS C:\Users\Krish Patel> CheckCMDExists "python"
True
PS C:\Users\Krish Patel> CheckCMDExists "python 3.10"
False
PS C:\Users\Krish Patel> CheckCMDExists "py"
True
PS C:\Users\Krish Patel> CheckCMDExists "tess"
False
```

Updated code for the function:
```
function CheckCMDExists {
    Param
    (
        [Parameter(Mandatory = $true)] [string] $command
    )

    $result = Get-Command $command -errorvariable getErr -erroraction 'silentlycontinue'
    if ($null -eq $result) {
        return $false
    }
    return $true
}
```

**Comment by KrishPatel13** [comment]
Issue 6: 
https://github.com/microsoft/vscode-python/issues/2559#issuecomment-420746291

Resolution:
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass", "-NoExit", "-Command", "poetry shell"

**Comment by KrishPatel13** [comment]
Issue 4: I think we have decide to use only Python 3.10.X currently as the not all features of OpenAdapt currently support python version 3.11.

https://github.com/OpenAdaptAI/OpenAdapt/issues/370#issuecomment-1642653014

**Comment by KrishPatel13** [comment]
made a PR here: https://github.com/OpenAdaptAI/OpenAdapt/pull/409
