### ISSUE TITLE
Intern Hire

### ISSUE THREAD

**Issue by biscuitdelicious** [OpenAdaptAI/OpenAdapt#381]
Hi there,

Looking for a job, you posted in on [hackernews](https://news.ycombinator.com/item?id=36573871). I'm currently based in Romania, who's got experience working with python and analyzing data. 

Attached my CV. If you have any questions, please feel free to ask.

Thanks!
[CV Delinschii Vladislav.pdf](https://github.com/OpenAdaptAI/OpenAdapt/files/12037156/CV.Delinschii.Vladislav.pdf)

**Comment by abrichr** [comment]
@biscuitdelicious thank you for your interest.

Github issues are for legitimate issues related to the OpenAdapt software. If you are interested in an internship please start by reading the README.
