### ISSUE TITLE
Implement Privacy API (involves major refactoring in scrub module)

### ISSUE THREAD

**Issue by KrishPatel13** [OpenAdaptAI/OpenAdapt#433]
### Feature request

We would like to have a common interface for scrubbing functions such that we could easily switch the provider based upon  our requirement.

Currently we have Presidio and Cape in line.

### Motivation

I was frustrated to change the scrub_text function to test cape and then move back to presidio. Hence, we would like to make it abstract and use a common interface for security provider that openadapt is currently using and/or testing.

**Comment by KrishPatel13** [comment]
@abrichr I had prepared some high-level implementations: Please see Page 4 and 5 here: https://docs.google.com/document/d/1Z6g6wNSExyWEFh9c0kQtIHCUQCiM7vxBkPbnb5jIzrU/edit?usp=sharing

**Comment by abrichr** [comment]
```
# we want to use https://docs.pydantic.dev/latest/

Class ScrubbingProvider:
    Name: str
    Capabilities: List[Modality]

    Def scrub_text(...):
        Raise NotImplemented()

Class PresidioScrubbingProvider:
    Def scrub_text(...):
        Pass   # implemented

Class ScrubbingProviderFactory:
    Def get_for_modality(modality: Modality) -> list[ScrubbingProvider]:
        Scrubbing_providers = ScrubbingProvider.get_children()  # see https://github.com/OpenAdaptAI/OpenAdapt/blob/main/openadapt/utils.py#L633 for implementation
        Filtered_providers = [provider for provider in scrubbing_providers if modality in provider.modalities]
        Return filtered_providers

```
```
Provider = PresidioScrubbingProvider()

# Or we instantiate indirectly based on capabilities:

Image_scrubbing_providers = ScrubbingProvider.get_for_modality(Modality.Image)

```
