### ISSUE TITLE
[Bug]: Error: Can't have direct dependency: 'en_core_web_trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.5.0/en_core_web_trf-3.5.0.tar.gz'

### ISSUE THREAD

**Issue by Mustaballer** [OpenAdaptAI/OpenAdapt#457]
### Describe the bug

I expected poetry to successfully publish openadapt on pypi, however I encountered this error.
```terminal
Error: Can't have direct dependency: 'en_core_web_trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.5.0/en_core_web_trf-3.5.0.tar.gz'
```

Possible solution:
- Remove this dependency from `pyproject.toml`
```pyproject.toml
[tool.poetry.dependencies.en_core_web_trf]
url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.5.0/en_core_web_trf-3.5.0.tar.gz"
```

### To Reproduce

When a PR is merged to main the 'Semantic Release and PyPi Publish' github action will run. In the `publish` job this error will be thrown.

**Comment by KrishPatel13** [comment]
On it, A PR will be lodged soon
