### ISSUE TITLE
Install spacy weights at runtime

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#461]
### Feature request

Pypi doesn't allow direct dependencies; see https://github.com/OpenAdaptAI/OpenAdapt/issues/457 .

We would like to automate the relevant step in the installation script at runtime within the scrubbing module (or wherever it is necessary), and remove the relevant step from installation.

@KrishPatel13 

### Motivation

Right now after `pip install openadapt` the user must manually install spacy weights. This is suboptimal.

**Comment by KrishPatel13** [comment]
PR: https://github.com/OpenAdaptAI/OpenAdapt/pull/462

**Comment by KrishPatel13** [comment]
Closing as completed in favour of https://github.com/OpenAdaptAI/OpenAdapt/pull/462
