### ISSUE TITLE
System tray notification on CLI record.py

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#475]
### Feature request

System tray notification on CLI record.py

**Comment by onejmi** [comment]
Hi @abrichr ,

I'd like to try to implement this feature. 

A few questions that I have are:

- When should the system tray notification should appear (I assume at the end of the recording process, maybe at the start as well after all event writers have started)?

- Are there any particular piece(s) of information that should be displayed on the notification (other than saying the recording started/ended)?

- Is there a particular library that I should invoke (i.e. in case something is already being used to display notifications, so I don't add an unnecessary dependency)? 

Thanks.

**Comment by abrichr** [comment]
Thanks for your patience @onejmi ! It looks like @0dm went ahead and implemented this.

Mea culpa on the delayed response, I've been a bit preoccupied with other projects and family issues, but am now heads down on OpenAdapt.

Please feel free to pick another issue, and/or review https://github.com/OpenAdaptAI/OpenAdapt/pull/510, and/or grab some time on my calendar to discuss how you can best contribute: https://www.getclockwise.com/c/richard-abrich/quick-meeting

Great to have you here! 😄
