### ISSUE TITLE
[Bug]: Issue when running install.sh (repo not found)

### ISSUE THREAD

**Issue by abhi1345** [OpenAdaptAI/OpenAdapt#501]
### Describe the bug

When running the Installation Script 

` /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/OpenAdaptAI/OpenAdapt/HEAD/install/install_openadapt.sh)"`

I'm getting the following output:

```
+ pythonCmd=python3.10
+ pythonVerStr='Python 3.10*'
+ pythonInstallerLoc=https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg
+ BRANCH=main
+ REPO=https://github.com/MLDSAI/OpenAdapt.git
+ REPO_URL=https://github.com/https://github.com/MLDSAI/OpenAdapt.git
+ CheckCMDExists brew
+ command=brew
+ command -v brew
+ return 0
+ CheckCMDExists git
+ command=git
+ command -v git
+ return 0
+ CheckCMDExists tesseract
+ command=tesseract
+ command -v tesseract
+ return 0
+ CheckPythonExists
+ CheckCMDExists python3.10
+ command=python3.10
+ command -v python3.10
+ return 0
+ return
+ '[' -d OpenAdapt ']'
+ RunAndCheck 'git clone https://github.com/https://github.com/MLDSAI/OpenAdapt.git' 'Clone git repo'
+ git clone https://github.com/https://github.com/MLDSAI/OpenAdapt.git
Cloning into 'OpenAdapt'...
remote: Not Found
fatal: repository 'https://github.com/https://github.com/MLDSAI/OpenAdapt.git/' not found
+ echo 'Failed: Clone git repo'
Failed: Clone git repo
+ Cleanup
+ '[' -d ../OpenAdapt ']'
+ exit 1
```

I think the url in the install.sh script needs to be updated. Additionally, the URL includes "https://github.com", so I think the $REPO variable needs to be truncated to just be "OpenAdaptAI/OpenAdapt". 

### To Reproduce

Steps to reproduce:
1. On MacOS, open new terminal an run ` /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/OpenAdaptAI/OpenAdapt/HEAD/install/install_openadapt.sh)"`
2. Observe output, should include `fatal: repository 'https://github.com/https://github.com/MLDSAI/OpenAdapt.git/' not found`

**Comment by abrichr** [comment]
Thank you for reporting and fixing @abhi1345 !
