### ISSUE TITLE
Implement Loom.com integration

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#57]
How can we make it extremely simple for people to create and share use cases?

- Loom: https://support.loom.com/hc/en-us/articles/360002228458-Does-Loom-have-an-open-API-
- others?

Capture user narration via speech to text e.g. https://github.com/openai/whisper

**Comment by abrichr** [comment]
@micol-altomare you might enjoy this one 😄

**Comment by dianzrong** [comment]
**Solution 1: Record videos with Loom **

Implementation:
- starter code is given on [https://dev.loom.com/docs/record-sdk/getting-started?_gl=1*16laoor*_gcl_aw*R0NMLjE2Mjk3NTA5MzAuQ2owS0NRandqbzJKQmhDUkFSSXNBRkc2NjdXQUVjS1NiRHUwcTM5M01Nc210aHBrQ0JsM0tJeWxoamNpV0REM2FyaHBPMWZ0OFVYUGVEd2FBdDlrRUFMd193Y0I.](Loom) but is written in React, Typescript or JavaScript so would also need some Python backend

Limitations:
- unable to open an account using my openadept.ai email (doesn't send a verification email)
- under the free account, guest accounts are restricted to a maximum number of 5 videos, and maximum duration of 5 minutes

**Comment by dianzrong** [comment]
**Solution 2: using a Python library**

Benefits:
- doesn't require another language

Implementation:
- most commonly, PyAutoGUI is used to take screenshots of the user's screen and OpenCV is used to take video from the user's camera


Limitations:
- needs the user to run the program in the command-line
- since PyAutoGUI is taking screenshots and it has a very slow frame rate, the video quality is very low

**Comment by dianzrong** [comment]
**Solution 3: using [Ziggeo](https://ziggeo.com/docs/how-tos/general/webrtc-live-streaming-flash-native/) API**

Benefits:

- has a Python SDK
- has built-in audio transcription capabilities
- can easily upload to youtube
- can put our own branding on it

Implementation:

- use their Python SDK

Limitations:

- may not be able to control the quality of the video (if the default/WebRTC recording method is used)

**Comment by dianzrong** [comment]
Can also use whisper in combination with the above solutions to communicate use-cases without having to demonstrate it

Benefit: 

- more accessible (for those who can't or find typing/clicking painful)
- also more human-friendly

Limitation:

- hard to line up audio and actions

**Comment by abrichr** [comment]
Thanks for taking the initiative on this @dianzrong ! 

> Solution 1: Record videos with Loom

I think this is preferable since Loom is the most popular and easy to use screen casting utility AFAIK. Here are some sources that might be helpful:

https://github.com/Ecno92/loom-dl
https://github.com/ytdl-org/youtube-dl/issues/27957

> Solution 2: using a Python library

We considered using PyAutoGUI to implement OpenAdapt, but ended up implementing it from scratch for various reasons. I think we would not want to go this route unless there is a compelling reason.

> Solution 3: using [Ziggeo](https://ziggeo.com/docs/how-tos/general/webrtc-live-streaming-flash-native/) API

This could be interesting, I haven't come across Ziggeo before. A glance at their pricing suggests they don't have a free tier however, which makes this less attractive.

Other options:

https://github.com/jonnekaunisto/simple-youtube-api

Uploading to YouTube might be the easiest to start. Eventually I think we also want to support Loom, but their docs suggest this can only be done from a web application. If that's the case then https://nicegui.io/ may also be relevant. It should be possible to interact with their HTTP API directly, e.g. using Python's `requests` library.

@dianzrong how comfortable are you with web development? Which approach sounds most interesting?

**Comment by dianzrong** [comment]
@abrichr I do not have experience with web development but would love to spend time on it. Also I feel like I might as well get started with Loom since we want it later. For now I think it would be fastest to get something working using niceGUI so I will start with that!

**Comment by abrichr** [comment]
Sounds good!

If we go with NiceGUI we will likely need to run custom JavaScript:
https://nicegui.io/documentation#run_javascript

See if you can get their JavaScript examples running from here:
https://dev.loom.com/docs/record-sdk/getting-started

It may be necessary to build a full stack application for this, but ideally
I think we would use NiceGUI.
