### ISSUE TITLE
Github Action to build via `openadapt.app.build`

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#574]
### Feature request

We wish to build MacOS and Windows binaries and have them stored to https://github.com/OpenAdaptAI/OpenAdapt/releases.

### Motivation

We want to add a "Download App" button to www.openadapt.ai

**Comment by abrichr** [comment]
@Mustaballer thoughts? 🙏 😄

**Comment by Mustaballer** [comment]
@abrichr, I've explored existing GitHub Actions tailored for releasing binaries on both Windows and Mac but haven't come across any that support both platforms simultaneously. It seems we'll need to incorporate separate steps to compile the binary distributions for each—Mac and Windows—and then upload them to the specifc release.

**Comment by abrichr** [comment]
Thank you @Mustaballer !

If I understand correctly, this means we should add two separate Github actions, one for each platform. Is that right?

**Comment by Mustaballer** [comment]
Yes, @abrichr we can set up two separate GitHub Actions workflows, one for each platform. Additionally, we can utilize parallel jobs within a single workflow to run both compilation processes simultaneously.

**Comment by abrichr** [comment]
Implemented in https://github.com/OpenAdaptAI/OpenAdapt/pull/618
