### ISSUE TITLE
Windows Installer for non-tech user

### ISSUE THREAD

**Issue by gawnecoding** [OpenAdaptAI/OpenAdapt#584]
### Feature request

Simple enough Windows installer that a very non-technical business user can have OpenAdapt running in 5 minutes. There should be no configuration options by default, only hidden under 'Advanced'. Includes skeleton terms of service. Easy to customize for white-labelling. 

### Motivation

Business users have no time, skills, or inclination to deal with a setup process in a Terminal. They expect it to "just work".

**Comment by abrichr** [comment]
Related: https://github.com/OpenAdaptAI/OpenAdapt/issues/574

**Comment by abrichr** [comment]
Implemented in https://github.com/OpenAdaptAI/OpenAdapt/pull/618
