### ISSUE TITLE
Explore LangChain

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#60]
How can we take advantage of https://python.langchain.com/en/latest/getting_started/getting_started.html ?

https://www.youtube.com/watch?v=aywZrzNaKjs

**Comment by abrichr** [comment]
@micol-altomare you might enjoy this one 😄

**Comment by micol-altomare** [comment]
Briefly, LangChain enhances LLMs (using OpenAI API, Hugging Face, etc.) by being able to connect them to source data (that's stored as vector embeddings, such as with the Pinecone API). We can also take advantage of two significant features: chaining and prompt templates.

The **source data** could take the form of:

- patient data, health records, booking calendar (in a text format, related to #77)
- bylaws, affidavits, other court documents (for law/policy researchers)
- (keyboard) events from OpenAdapt (still exploring this)

LangChain's LLM could then interface with OpenAdapt in several ways:

**1. (The user's source data and) LLM prompts informs the next workflow**
Usecase example: a) connecting the LLM to a physician's entire database, b) asking the LLM to list which patients to see next based on outstanding treatment needs, last visit, etc., c) using OpenAdapt to book each patient, produce automated calls/emails to confirm appointments
Example: ask the LLM to choose what's the best workflow from a set of workflows
**2. The workflow informs a) the prompt template itself; or b) the dynamic inputs**
Example: LLM input -> perform a workflow that achieves a certain output -> use that output to inform LLM input for the next workflow
**3. Asking LangChain to modify an existing workflow (eg. make the workflow more efficient)**

Implementation:
- after importing LangChain, this documentation (https://python.langchain.com/en/latest/modules/prompts/prompt_templates/getting_started.html) will allow us to generate output from a prompt (and create templates) which would then be passed as the prompt to inform OpenAdapt's next workflow

My biggest considerations for LangChain use:
- Scalability: Is it limited by the use of user-specific source data?
