### ISSUE TITLE
[Bug]: Mouse flickers during capture on Windows devices

### ISSUE THREAD

**Issue by gawnecoding** [OpenAdaptAI/OpenAdapt#607]
### Describe the bug

We expect the user's system to be relatively unaffected by the capture process. When capturing on a Windows device the mouse consistently flickers, even when resource utilization is low. There seems to be an issue with FFMpeg generally (try it in terminal). 

There's a long-running FFMpeg issue on this topic: https://stackoverflow.com/questions/34023630/how-to-avoid-mouse-pointer-flicker-when-capture-a-window-by-ffmpeg . One area to explore is whether using -dshow instead of -gdigrab helps? 

### To Reproduce

Start capture on a Windows device
Go about using your system (eg. moving mouse)
Note the continuous, distracting flickering of the mouse

**Comment by abrichr** [comment]
Fixed in https://github.com/OpenAdaptAI/OpenAdapt/pull/628
