### ISSUE TITLE
[Bug]: `poetry run install-dashboard` gives error on Windows

### ISSUE THREAD

**Issue by KrishPatel13** [OpenAdaptAI/OpenAdapt#693]
### Describe the bug

I expected `poetry run install-dashboard` to unr successfully, but it gave an error as seen below:
![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/65433817/c44d50bd-1cca-46a1-88cb-452a09b24b4a)

### To Reproduce

Follow setup steps till the command, `poetry run install-dashboard`.

**Comment by KrishPatel13** [comment]
I did some research for the causer of this error:
![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/65433817/9466776a-e84b-4737-ab45-9c70de97ccb3)

I found that my pc did not have `nvm` installed. FYI: `nvm` = node version manager.

Further, I found out that:
The install script for windows (ps1) did not install `nvm` successfully:
![image](https://github.com/OpenAdaptAI/OpenAdapt/assets/65433817/92a10623-6fc0-44bc-b412-9a77d7e7ac41)

So, in order to resolve this for windows, we shall investigate the install scripts' nvm installation part.

**Comment by KrishPatel13** [comment]
Looks like, the code in the install script was correct, just that we had to mention about installing `nvm` in the manual setup.

As I followed the manual setup instructions and this was mentioned any where.

**Comment by KrishPatel13** [comment]
Resolved here: https://github.com/OpenAdaptAI/OpenAdapt/pull/694

**Comment by abrichr** [comment]
Possibly related: https://github.com/OpenAdaptAI/OpenAdapt/issues/682
