### ISSUE TITLE
Design: Prompting

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#70]
What are some of the different ways we can structure our prompts and expected outputs? What is currently in place? What are the tradeoffs?

**Comment by jesicasusanto** [comment]
Hi @abrichr ! Below is what I think about this issue which is related to #35   :
1. Template-Based Prompts
in my SegmentAnything pull request #35 I used a template-prompt with placeholders for the task goal, previously recorded input events, and the description of the screenshot that has been converted to text with OCR. 
Trade offs : 
-It is lengthy and might exceed the model's token limit, requiring truncation or modification of the prompt.
-The consistency of the model's output might vary depending on the complexity of the task and the quality of the templates.

2. Prompts with example output
`Please generate a new InputEvent with the following details:

Name: ClickEvent
Timestamp: 1621800000
Recording Timestamp: [recording_timestamp]
Screenshot Timestamp: [screenshot_timestamp]
Window Event Timestamp: [window_event_timestamp]
Mouse X: 100
.
.
etc
`
Easier to extract information and convert output to an InputEvent object.
Tradeoffs :
Sacrifice generalizability and flexibility such as potentially limiting the model's ability to handle variations

3. Single Prompt Single Output
For each InputEvents attribute, we generate individual prompts and collect the corresponding expected outputs for each attribute of the InputEvent class.
Tradeoffs:
Some attributes may have interdependencies, and generating them in isolation may lead to inconsistent or incompatible inputs.

Thank you I hope this helps with the research!🙏

**Comment by abrichr** [comment]
Jinja2 templates are working for now.
