### ISSUE TITLE
[Bug]: recording from Dashboard doesn't display toast notifications

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#721]
### Describe the bug

When recording from the dashboard, there are no toast notifications that are displayed. This is inconsistent with the behavior when recording from the tray icon.

This task involves refactoring notifications so that they occur regardless from where the recording started.

### To Reproduce

- Start Dashboard
- Click "Start Recording"

**Comment by abrichr** [comment]
When addressing this, it may make sense to address https://github.com/OpenAdaptAI/OpenAdapt/blob/main/openadapt/app/tray.py#L80 as well:

```
# TODO: remove once https://github.com/niklashenning/pyqt-toast/issues/9
```

https://github.com/niklashenning/pyqt-toast/issues/9 has been completed since then.

**Comment by abrichr** [comment]
@KIRA009 Until this is resolved, let's disable recording from dashboard (e.g. comment out Record button).

**Comment by KIRA009** [comment]
This has been addressed

**Comment by abrichr** [comment]
Fixed in https://github.com/OpenAdaptAI/OpenAdapt/pull/809
