### ISSUE TITLE
[Bug]: HTTP Error 400: Can't have direct dependency: openai-whisper

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#740]
### Describe the bug

https://github.com/OpenAdaptAI/OpenAdapt/actions/runs/9484457521/job/26135042643:

```
 - Uploading openadapt-0.31.0-py3-none-any.whl 100%
HTTP Error 400: Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information. | b"<html>\n <head>\n  <title>400 Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n \n <body>\n  <h1>400 Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nCan&#x27;t have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n\n\n \n"
Error: Process completed with exit code 1.
```

While this workflow fails, the version bump succeeds:

https://github.com/OpenAdaptAI/OpenAdapt/commit/1338fa22391af12b8d867b0cbc9f1429c4eeb450

### To Reproduce

Merge a PR

**Comment by abrichr** [comment]
@KIRA009 your thoughts on this would be very much appreciated! 🙏

**Comment by abrichr** [comment]
@KIRA009 the "publish to pypi" step failed: https://github.com/OpenAdaptAI/OpenAdapt/actions/runs/9516888546

```
Publishing openadapt (0.33.1) to PyPI
 - Uploading openadapt-0.33.1-py3-none-any.whl 0%

 - Uploading openadapt-0.33.1-py3-none-any.whl 100%
HTTP Error 400: Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information. | b"<html>\n <head>\n  <title>400 Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n \n <body>\n  <h1>400 Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nCan&#x27;t have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n\n\n \n"
Error: Process completed with exit code 1.
```

**Comment by abrichr** [comment]
The same step failed again in https://github.com/OpenAdaptAI/OpenAdapt/actions/runs/9529191944/job/26267849108:

```
Installing the current project: openadapt (0.33.2)
Using a plaintext file to store credentials
Building openadapt (0.33.2)
  - Building sdist
  - Built openadapt-0.33.2.tar.gz
  - Building wheel
  - Built openadapt-0.33.2-py3-none-any.whl

Publishing openadapt (0.33.2) to PyPI
 - Uploading openadapt-0.33.2-py3-none-any.whl 0%
 - Uploading openadapt-0.33.2-py3-none-any.whl 13%
 - Uploading openadapt-0.33.2-py3-none-any.whl 40%

 - Uploading openadapt-0.33.2-py3-none-any.whl 100%
HTTP Error 400: Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information. | b"<html>\n <head>\n  <title>400 Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n \n <body>\n  <h1>400 Can't have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nCan&#x27;t have direct dependency: openai-whisper@ git+https://github.com/openai/whisper.git. See https://packaging.python.org/specifications/core-metadata for more information.\n\n\n \n"
Error: Process completed with exit code 1.
```

**Comment by abrichr** [comment]
Thanks @KIRA009 ! I believe we did this with `oa_pynput` and `oa_atomacos`. Why do we need to do this with whisper? It appears to be pointing to the official release.

**Comment by abrichr** [comment]
Another failure: https://github.com/OpenAdaptAI/OpenAdapt/actions/runs/9584045022/job/26426713466#step:5:592

**Comment by abrichr** [comment]
Another: https://github.com/OpenAdaptAI/OpenAdapt/actions/runs/9630522661/job/26561764301#step:4:692

**Comment by abrichr** [comment]
Let's look into alternatives. If not, we need to publish https://github.com/OpenAdaptAI/whisper to pypi with the name `oa_whisper`.

**Comment by KIRA009** [comment]
I have taken a look at other alternatives, but looks like whisper is the best bet at the moment for models that can run locally, and also provide the timestamps for the transcribed words

**Comment by abrichr** [comment]
Thank you @KIRA009 .

It seems others may already be uploading to pypi: https://github.com/openai/whisper/pull/681

Can we re-use one of those? e.g. https://pypi.org/project/openai-whisper/ or https://pypi.org/project/whisper.ai/ or https://pypi.org/project/whisper-openai/

**Comment by KIRA009** [comment]
Unfortunately all of those project's last update were on 2022, while the official package's last update was on 2023, so the official package is more updated. The `word_timestamps` feature was introduced in 2023 - https://github.com/openai/whisper/commit/500d0fe9668fae5fe2af2b6a3c4950f8a29aa145 - so the alternative packages cannot be used to replace the official one.

However, this only seems to be an issue with poetry - https://github.com/python-poetry/poetry/issues/8673, install via `pip` works. There is an MR that fixes it for poetry - https://github.com/openai/whisper/pull/1887, that has been merged, but since the package has not been updated on PyPI after that, we are not able to use that.

**Comment by abrichr** [comment]
Fixed by post-installing in https://github.com/OpenAdaptAI/OpenAdapt/pull/865
