### ISSUE TITLE
Fix Posthog events

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#768]
![Image](https://github.com/OpenAdaptAI/OpenAdapt/assets/774615/b897e2b4-14e7-4deb-942c-87c3d1102da4)

- we would like there to be zero "None" events (all of these should have some more descriptive categorization)
- events named after a recording (e.g. "text someone") should be combined into the "delete", "replay", or "visualize" event

**Comment by KIRA009** [comment]
This has been addressed
