### ISSUE TITLE
[Bug]: Not able to create a recording

### ISSUE THREAD

**Issue by absha03** [OpenAdaptAI/OpenAdapt#790]
### Describe the bug

I expected it start recording while running: python -m openadapt.record "testing out openadapt" instead got this error:

(openadapt-py3.10) C:\Users\abhis\openAdapt\OpenAdapt>python -m openadapt.record "testing out openadapt"
2024-06-21 16:31:50.917 | INFO     | openadapt.utils:wrapper_logging:676 -  -> Enter: record(testing out openadapt, None, None, None, False)
2024-06-21 16:31:50.969 | INFO     | openadapt.db.crud:release_db_lock:871 - Database lock released.
2024-06-21 16:31:50.971 | INFO     | openadapt.db.crud:acquire_db_lock:853 - Database lock acquired.
2024-06-21 16:31:50.972 | INFO     | __main__:record:1168 - task_description='testing out openadapt'
2024-06-21 16:31:50.974 | INFO     | openadapt.utils:wrapper_logging:676 -  -> Enter: create_recording(testing out openadapt)
2024-06-21 16:31:51.026 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (21276), thread 'MainThread' (20956):Traceback (most recent call last):

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
    |    |       -> <function DefaultDialect.do_execute at 0x000001B5D5DBDCF0>
    |    -> <sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x000001B5D9EE3880>
    -> <sqlalchemy.engine.base.Connection object at 0x000001B5E8A5FA30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
    |      |       |          -> (1719001910.9778485, 3840, 2160, 0.5, 4.0, 'win32', 'testing out openadapt', None, '{"ROOT_DIR_PATH": "C:\\\\Users\\\\abhis\\...
    |      |       -> 'INSERT INTO recording (timestamp, monitor_width, monitor_height, double_click_interval_seconds, double_click_distance_pixels...
    |      -> <method 'execute' of 'sqlite3.Cursor' objects>
    -> <sqlite3.Cursor object at 0x000001B5E89F7BC0>

sqlite3.OperationalError: no such table: recording

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           |         |     -> {'__name__': '__main__', '__doc__': 'Script for creating Recordings.\n\nUsage:\n\n    $ python -m openadapt.record "<descript...
           |         -> <code object <module> at 0x000001B5B408F100, file "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\record.py", line 1>
           -> <function _run_code at 0x000001B5B401AA70>

  File "C:\Users\abhis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': 'Script for creating Recordings.\n\nUsage:\n\n    $ python -m openadapt.record "<descript...
         -> <code object <module> at 0x000001B5B408F100, file "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\record.py", line 1>

  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\record.py", line 1414, in <module>
    fire.Fire(record)
    |    |    -> <function record at 0x000001B5E896FC70>
    |    -> <function Fire at 0x000001B5DAB4B6D0>
    -> <module 'fire' from 'C:\\Users\\abhis\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\openadapt-8xtrqwsq-py3.10\\lib\\site-pac...

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      |     |          |     |                 |        -> 'record.py'
                      |     |          |     |                 -> {}
                      |     |          |     -> Namespace(verbose=False, interactive=False, separator='-', completion=None, help=False, trace=False)
                      |     |          -> ['testing out openadapt']
                      |     -> <function record at 0x000001B5E896FC70>
                      -> <function _Fire at 0x000001B5DABF32E0>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    |                           -> <function _CallAndUpdateTrace at 0x000001B5DABF3400>
    -> <function record at 0x000001B5E896FC70>

> File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                |   |          -> {}
                |   -> ['testing out openadapt', None, None, None, False]
                -> <function record at 0x000001B5E896FC70>

  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\utils.py", line 686, in wrapper_logging
    result = func(*args, **kwargs)
             |     |       -> {}
             |     -> ('testing out openadapt', None, None, None, False)
             -> <function record at 0x000001B5E896FD90>

  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\record.py", line 1170, in record
    recording = create_recording(task_description)
                |                -> 'testing out openadapt'
                -> <function create_recording at 0x000001B5E896FAC0>

  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\utils.py", line 686, in wrapper_logging
    result = func(*args, **kwargs)
             |     |       -> {}
             |     -> ('testing out openadapt',)
             -> <function create_recording at 0x000001B5E896FA30>

  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\record.py", line 876, in create_recording
    recording = crud.insert_recording(session, recording_data)
                |    |                |        -> {'timestamp': 1719001910.9778485, 'monitor_width': 3840, 'monitor_height': 2160, 'double_click_distance_pixels': 4, 'double_c...
                |    |                -> <sqlalchemy.orm.session.Session object at 0x000001B5E8A00F40>
                |    -> <function insert_recording at 0x000001B5E8957D00>
                -> <module 'openadapt.db.crud' from 'C:\\Users\\abhis\\openAdapt\\OpenAdapt\\openadapt\\db\\crud.py'>

  File "C:\Users\abhis\openAdapt\OpenAdapt\openadapt\db\crud.py", line 259, in insert_recording
    session.commit()
    |       -> <function Session.commit at 0x000001B5D9DB72E0>
    -> <sqlalchemy.orm.session.Session object at 0x000001B5E8A00F40>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
    |    |            |               |    -> False
    |    |            |               -> <sqlalchemy.orm.session.Session object at 0x000001B5E8A00F40>
    |    |            -> <function SessionTransaction.commit at 0x000001B5D9DB6290>
    |    -> <sqlalchemy.orm.session.SessionTransaction object at 0x000001B5E8A00D30>
    -> <sqlalchemy.orm.session.Session object at 0x000001B5E8A00F40>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
    |    -> <function SessionTransaction._prepare_impl at 0x000001B5D9DB6200>
    -> <sqlalchemy.orm.session.SessionTransaction object at 0x000001B5E8A00D30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
    |    |       -> <function Session.flush at 0x000001B5D9DCCF70>
    |    -> <sqlalchemy.orm.session.Session object at 0x000001B5E8A00F40>
    -> <sqlalchemy.orm.session.SessionTransaction object at 0x000001B5E8A00D30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 3444, in flush
    self._flush(objects)
    |    |      -> None
    |    -> <function Session._flush at 0x000001B5D9DCD120>
    -> <sqlalchemy.orm.session.Session object at 0x000001B5E8A00F40>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 3583, in _flush
    with util.safe_reraise():
         |    -> <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         -> <module 'sqlalchemy.util' from 'C:\\Users\\abhis\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\openadapt-8xtrqwsq-py3.10\\li...

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
    |      -> <function raise_ at 0x000001B5D576B490>
    -> <module 'sqlalchemy.util.compat' from 'C:\\Users\\abhis\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\openadapt-8xtrqwsq-py3...

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 3544, in _flush
    flush_context.execute()
    |             -> <function UOWTransaction.execute at 0x000001B5D9D3B880>
    -> <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001B5E8A5F280>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
    |   |       -> <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000001B5E8A5F280>
    |   -> <function SaveUpdateAll.execute at 0x000001B5D9DB41F0>
    -> SaveUpdateAll(mapped class Recording->recording)

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
    |    |         |               -> <function save_obj at 0x000001B5D9D39360>
    |    |         -> <module 'sqlalchemy.orm.persistence' from 'C:\\Users\\abhis\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\openadapt-8xtrqwsq...
    |    -> <sqlalchemy.util._preloaded._ModuleRegistry object at 0x000001B5D55ADBD0>
    -> <module 'sqlalchemy.util' from 'C:\\Users\\abhis\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\openadapt-8xtrqwsq-py3.10\\li...

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    _emit_insert_statements(
    -> <function _emit_insert_statements at 0x000001B5D9D39990>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\orm\persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             |          -> <function Connection._execute_20 at 0x000001B5D5CFCA60>
             -> <sqlalchemy.engine.base.Connection object at 0x000001B5E8A5FA30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           |    |     |             |               -> {'compiled_cache': {(<sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x000001B5D9EE3880>, ('0', <class ...
           |    |     |             -> immutabledict({})
           |    |     -> ({'monitor_height': 2160, 'monitor_width': 3840, 'task_description': 'testing out openadapt', 'config': {'ROOT_DIR_PATH': 'C:...
           |    -> <sqlalchemy.engine.base.Connection object at 0x000001B5E8A5FA30>
           -> <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x000001B5E8A5FB80>>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
           |          -> <function Connection._execute_clauseelement at 0x000001B5D5CFC8B0>
           -> <sqlalchemy.engine.base.Connection object at 0x000001B5E8A5FA30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          |    -> <function Connection._execute_context at 0x000001B5D5CFCB80>
          -> <sqlalchemy.engine.base.Connection object at 0x000001B5E8A5FA30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
    |    -> <function Connection._handle_dbapi_exception at 0x000001B5D5CFCD30>
    -> <sqlalchemy.engine.base.Connection object at 0x000001B5E8A5FA30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
    |    -> <function raise_ at 0x000001B5D576B490>
    -> <module 'sqlalchemy.util' from 'C:\\Users\\abhis\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\openadapt-8xtrqwsq-py3.10\\li...

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
    |    |       -> <function DefaultDialect.do_execute at 0x000001B5D5DBDCF0>
    |    -> <sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x000001B5D9EE3880>
    -> <sqlalchemy.engine.base.Connection object at 0x000001B5E8A5FA30>

  File "C:\Users\abhis\AppData\Local\pypoetry\Cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
    |      |       |          -> (1719001910.9778485, 3840, 2160, 0.5, 4.0, 'win32', 'testing out openadapt', None, '{"ROOT_DIR_PATH": "C:\\\\Users\\\\abhis\\...
    |      |       -> 'INSERT INTO recording (timestamp, monitor_width, monitor_height, double_click_interval_seconds, double_click_distance_pixels...
    |      -> <method 'execute' of 'sqlite3.Cursor' objects>
    -> <sqlite3.Cursor object at 0x000001B5E89F7BC0>

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: recording
[SQL: INSERT INTO recording (timestamp, monitor_width, monitor_height, double_click_interval_seconds, double_click_distance_pixels, platform, task_description, video_start_time, config, original_recording_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (1719001910.9778485, 3840, 2160, 0.5, 4.0, 'win32', 'testing out openadapt', None, '{"ROOT_DIR_PATH": "C:\\\\Users\\\\abhis\\\\openAdapt\\\\OpenAdapt\\\\openadapt", "PRIVATE_AI_API_KEY": "******************Y>", "REPLICATE_API_TOKEN": ... (1764 characters truncated) ... DASHBOARD_CLIENT_PORT": 5173, "DASHBOARD_SERVER_PORT": 8080, "SOM_SERVER_URL": "<SOM_SERVER_URL>", "UNIQUE_USER_ID": "", "DEFAULT_ADAPTER": "openai"}', None)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

(openadapt-py3.10) C:\Users\abhis\openAdapt\OpenAdapt>

### To Reproduce

start recording while running: python -m openadapt.record "testing out openadapt" on windows

**Comment by abrichr** [comment]
Thank you for reporting this @absha03 !

> `no such table: recording`

This suggests that the database has not been initialized correctly. Can you please follow the instructions step by step in https://github.com/OpenAdaptAI/OpenAdapt?tab=readme-ov-file#manual-setup ?

**Comment by absha03** [comment]
Hi @abrichr thanks for you reply, I have installed the requisites, including tesseract and nvm and node powershel 7 for windows, python 3.10 on the setup now I get this error: 


(openadapt-py3.10) PS C:\Users\abhis\openAdapt\OpenAdapt> poetry run postinstall

Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to c:\users\abhis\appdata\local\temp\pip-req-build-uchlgw27  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git 'C:\Users\abhis\AppData\Local\Temp\pip-req-build-uchlgw27'
  Resolved https://github.com/facebookresearch/detectron2.git to commit 70f454304e1a38378200459dd2dbca0f0f4a5ab4
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Pillow>=7.1 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from detectron2==0.6) (10.3.0)
Requirement already satisfied: matplotlib in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from detectron2==0.6) (3.9.0)
Requirement already satisfied: pycocotools>=2.0.2 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (2.0.8)
Requirement already satisfied: termcolor>=1.1 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (2.4.0)
Requirement already satisfied: yacs>=0.1.8 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (0.1.8)
Requirement already satisfied: tabulate in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (0.9.0)
Requirement already satisfied: cloudpickle in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (3.0.0)
Requirement already satisfied: tqdm>4.29.0 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from detectron2==0.6) (4.66.4)
Requirement already satisfied: tensorboard in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (2.17.0)
Requirement already satisfied: fvcore<0.1.6,>=0.1.5 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (0.1.5.post20221221)
Requirement already satisfied: iopath<0.1.10,>=0.1.7 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (0.1.9)
Requirement already satisfied: omegaconf<2.4,>=2.1 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (2.3.0)
Requirement already satisfied: hydra-core>=1.1 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (1.3.2)
Requirement already satisfied: black in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from detectron2==0.6) (23.7.0)
Requirement already satisfied: packaging in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from detectron2==0.6) (23.2)
Requirement already satisfied: numpy in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (1.26.4)
Requirement already satisfied: pyyaml>=5.1 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (6.0.1)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from hydra-core>=1.1->detectron2==0.6) (4.9.3)
Requirement already satisfied: portalocker in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from iopath<0.1.10,>=0.1.7->detectron2==0.6) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->detectron2==0.6) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->detectron2==0.6) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->detectron2==0.6) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->detectron2==0.6) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->detectron2==0.6) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->detectron2==0.6) (2.9.0.post0)
Requirement already satisfied: colorama in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from tqdm>4.29.0->detectron2==0.6) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from black->detectron2==0.6) (8.1.7)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from black->detectron2==0.6) (1.0.0)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from black->detectron2==0.6) (0.12.1)
Requirement already satisfied: platformdirs>=2 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from black->detectron2==0.6) (4.2.1)
Requirement already satisfied: tomli>=1.1.0 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from black->detectron2==0.6) (2.0.1)
Requirement already satisfied: absl-py>=0.4 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from tensorboard->detectron2==0.6) (2.1.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from tensorboard->detectron2==0.6) (1.62.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from tensorboard->detectron2==0.6) (3.6)
Requirement already satisfied: protobuf!=4.24.0,<5.0.0,>=3.19.6 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from tensorboard->detectron2==0.6) (4.25.3)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from tensorboard->detectron2==0.6) (57.4.0)
Requirement already satisfied: six>1.9 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from tensorboard->detectron2==0.6) (1.16.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from tensorboard->detectron2==0.6) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\abhis\appdata\local\pypoetry\cache\virtualenvs\openadapt-8xtrqwsq-py3.10\lib\site-packages (from tensorboard->detectron2==0.6) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from werkzeug>=1.0.1->tensorboard->detectron2==0.6) (2.1.5)
Requirement already satisfied: pywin32>=226 in c:\users\abhis\appdata\local\programs\python\python310\lib\site-packages (from portalocker->iopath<0.1.10,>=0.1.7->detectron2==0.6) (306)
Original directory: C:\Users\abhis\openAdapt\OpenAdapt
Dashboard directory: C:\Users\abhis\openAdapt\OpenAdapt\openadapt\app\dashboard
Changed directory to: C:\Users\abhis\openAdapt\OpenAdapt\openadapt\app\dashboard
./entrypoint.ps1 : File C:\Users\abhis\openAdapt\OpenAdapt\openadapt\app\dashboard\entrypoint.ps1 cannot be loaded
because running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./entrypoint.ps1
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
Error running entrypoint script: Command '['powershell', './entrypoint.ps1']' returned non-zero exit status 1.
Reverted to original directory: C:\Users\abhis\openAdapt\OpenAdapt

**Comment by abrichr** [comment]
Thank you @absha03. Please try the solution described here: https://github.com/OpenAdaptAI/OpenAdapt/issues/626#issuecomment-2187362965

**Comment by absha03** [comment]
Hi @abrichr , I am past the npm issue, now pls help with this alembic error: 
PS C:\Users\abhis\openAdapt\OpenAdapt\openadapt> alembic upgrade head
alembic: The term 'alembic' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by absha03** [comment]
opened a seperate issue for above
