### ISSUE TITLE
Implement marketplace

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#91]
This task involves creating a full stack web app (eg with FastAPI/Vuetify) that lets users share their automations.

**Comment by jesicasusanto** [comment]
Hi @abrichr , Here is my high-level implementation for this issue :
- Build web app with Backend FastAPI and Frontend Nuxt JS
- Define a get route for the home page
- Define a post route for sharing automations in the form of recording.
- Define a post route for sharing automations in bulk

UI Mockup :
Home page
<img width="426" alt="image" src="https://github.com/MLDSAI/OpenAdapt/assets/87709055/c873a17d-c20c-4023-80cf-d6345028ac86">
Sharing page
<img width="426" alt="image" src="https://github.com/MLDSAI/OpenAdapt/assets/87709055/40d17cd0-e604-4056-9812-92af2ff7edaa">

TODO : Discover page, Log in page

Questions:
Should we allow users to discover other users' automations as well?
How will users register and authenticate themselves?
What database system will be used to store user profiles, automations, and other relevant data? 
Thank you!🙏

**Comment by PeterTTDev** [comment]
Great work Jessica! I have some complementary suggestions that align with some of the mockups you've done so far:

Above the fold:
![image](https://github.com/MLDSAI/OpenAdapt/assets/122234940/b26f8bcd-8a46-4bcf-97c1-2bb212a326ef)

Rationale: 
- Horizontally-oriented carousal that immediately presents multiple workflows with mouse-over autoplay - has the effect of explaining (a) the product and (b) the multitude of applications that are possible. 
- Search bar and button-cloud underneath the carousel that populates search results underneath the fold: allows users to find what is relevant to them. 

Below the fold:
![image](https://github.com/MLDSAI/OpenAdapt/assets/122234940/23bdeaed-ee83-4463-98b8-fba80e604ed7)
Linear-arranged scrolling options with larger mouse-over autoplay videos and more detailed text descriptions. A very common UI design for marketplace-style options. Simple so as not to overwhelm the user with competing calls-to-action. 

These are rough ideas for now.
